package br.unirio.visualnrp.calc.analysis;

import br.unirio.visualnrp.algorithm.search.Solution;
import br.unirio.visualnrp.calc.fitness.ProfitRiskFitnessCalculator;
import br.unirio.visualnrp.model.Instance;
import br.unirio.visualnrp.model.MaximumValues;
import br.unirio.visualnrp.model.MaximumValuesList;
import br.unirio.visualnrp.model.Project;
import br.unirio.visualnrp.reader.MaximumValuesReader;
import br.unirio.visualnrp.reader.RequirementReader;

/**
 * Class that analizes the best solutions under the OPR-NRP formulation
 * 
 * @author Marcio
 */
public class ProfitRiskAnalysis
{
	/**
	 * Best solutions generated by ILS
	 */
	private static String[] ILS_CRO_INSTANCES =
	{
		// nrp1
		"[--SSSS-S--S-----SS---S-----SS-SS-S---S----S---S----S----SS-SS-SSSS--S-SS--SS-S-S--S-SS-S-SS----S-S--]",
		"[---SSS-SS-S-----SS-S----S-S---SS----SS----S---S----S--------SS-SSS--S-SSS-SS-S-S--S-SS-S-SS-S--S-S--]",
		"[---SSS-SS-------SS--------SSS-S-----SS----SS-------S--------SSSSSS--S-SSS--S---S--S-SS-S-SS----S-S--]",

		// nrp2
		"[S-S-S-SSS------SS---SS-S--S--S-----S-----SS--S---S--------S--S-SS-S--------S--S-S---SS-SS----------------SS---SS-----S--S--S--S---S-SS---S-----S--S--S-S--S--S--S--S-------S--SSS----SS-SS--SS--SS--S---SSS--S---S--S--S-S-S-SS-SS-SSS-S----SS---S-S--S--S----S-SS------------S---S-S---SS----SS-S-SSS-----S--------S-S-SS-SSSS---S-----S--SSS--S-----SS-----S------SS-SS-S--S-----S--S-----SS------------SS--S-S--SS-SS----S-------S---S---SS----S-S---SS-S------SS-SS--SS----S----S---SS-------S-------S--S-SS-S--]",
		"[S-S-S-SSS------SS----S-S--SSSS-----S-----SS--S----S-------S----SSSS----S---S-S-SS---S---S-S-------S------SS---SS------S----S--S---S-SS---S-----S--S--SSS--S--S--S--S-----S-S---SS----SS-SS--S---S---S--SSSS--S---S--S--S-S--SSS----SS-SS----SS---S-S----------S--S-------S---------SSSS--S----SS-S-SSS---S-S--------S-S-SS-S-SS---S---S----S-SS-S----S-S-----S------S--S--S--S-----S--S-S----S--S--S-------S--S-S---S-S---S-S-------S--SS----S--S-S-S---S--SS------S-SSS-SS----S-S--SS---S-------S----------S-SSSS--]",
		"[S-----S--------S----SS----S--S-----S-----SS-------S-------S--S-S-SS-------------S---SS-SS-------------S---S---SS-----------S--SS--S-SS---S-----S--S-SS-S--S--S--SS---------S---S--S-----SS--SS--S---S--SSSS------S--S----S--SSS-SS-SS-SS----S----S-S-----S----SS-S--S----S----S-------S--S----SS---S-SS--S----------S-SS-S----S---S---S-S----S--S---SS---S---S------SS-SS-S--S-----------SS--S--S--S----------S-----S-SS----S-S--S--S--SS----S--S-S-S-S-SS---------S--S--SSS---S----S---SS-S----------------S-SS-S--]",

		// nrp3
		"[-SSS-SSS-S-S--S-S--S--SS-S-----SSS--SS--S-S-S--SS---S-S-S---S-SS----SS-S--S-S---S---S-S--SS-SSSS--S----SSSSS-SSSSSS------S-S--SS-SSS-SSS-SSSS---SSSS-S-S--S--S--S---S---SSSSS-SSSSSS-S-SSSSSS---S-SS-S-SSSS---SS-SS--S------S--S---S-S----SS-SSSS-S--S-S-S-S-S--------SS-S----SS-SS--SS----SS-SS---S-S-S----S-S-S---SS-S--SSS--SSS--------S--S----S----S-SS-S-SS----SSS---S-SS-S--SSS-S-SS--SSSSSS---S-SS---SS----SSS-SS-SS-S-S--S---SSSS--SS----S-SS-SSSSSSSS-S-S-S-----S-S---S-SS-SS-S-S-SS---S-S-SSSS-S-SS--SSSS-]",
		"[-SSS-SS--S-S--S-S--S--SS-S-S---SSS--SS--S-S-S---S---S-S-S------S----SS-S--S-S---S--S-SS--S--SSSSS-S----SSS---SSSSSS-S----S-SS-SS-SSS-SS--S-SS---SSSS-S-SS-S--S--S--SS---SSSSS-SSSSSS-S-SSSS-S----SSSSS-SS-S---SS-SS-SS---SS----S---S-S--S-SS-SSS-----SSS-S---S------S-SS-SS---SSSSS--SS-------SS-SSSS--S----S-S-S---SS-S---SS-SSSS--------S--S---SS----S--S-S-SS--S-SSS---S-SS-S--SSSSS-SS--SSSSSS--SS-SS--S-S---SSSS-SS-S--S----S---SSS-S-SSS---SSSS-SSSSS-SS-S---SS----S-S---S-SS--S-S-S-SS-S-S-S-SSSS--SSS----SS-]",
		"[-SSS-SSS-S-S--S-S--S--SS-S-----SSS--SSS---SS----S---S--SS---S--SS---SS-S--S-S--SS--S-SSS-S--SSS---S----S----S-S-----SS---S-S----SSSS--S---S-S----S---S-S------SSS---S----SSSS-S-SSSSSS-SSSS-S---SSSS-S-SSSS---S---S-S--S-------S---S-S-SSS---SS--S----S--S---S-S----S-SS-S-----SSS--SSS--------S-S--SS------SS--S-S-SSSSS---S-SSS-S--SS---S------SS----S---S--SS-S-SSS----S--S-S-----SS-SS--SSSS-S---S--S---S----S-SS-S--S---S--S--S--S-S---SS---S-S--SSSSS-SS-S-S-SS-S--------S-SS-SS---S-SS-S-S-SSSSSS-SSSS--S-SS-]",

		// nrp4
		"[S-S--SS---S--------SS-SSS-S-SSS--SSS-S-SSSS---S-S-S--S--S-S----S-SS-S-S-----SS---SSS---S--SS--SSS-SS--S-SSS--SSSSSSS-S------S--SS----SSSSS--S--S-------S---SS--S-----SSS--S-SSS-S-----S--SSSSS-SS----S--S-SSSSSS-S-S--S-SSS-SSS---S-S----SS----S----SS-S-S-SS-S-SS-SSS--S-S-S----S-SSS-SS-SS-S-S---SSSSS---S--SS--SSS----S----SSS--S-SSS-S-SSSSS-SSS-SSSS-S-SS------S---SSS-S---S--------S-SS------S-SSS--SSSS-SS-S--S-SSS--------SS---S-S-S-SSSS---S---S---SSSSSSSSS-----S-SS---SS-SSS-S----SSS--SS-SS--S--S---SS--S----S-S----S-SS---S--S-S-----S-SS--S-SS-S-SS---------SSSSS--SSS--SSSS----S----SS---SS--S-SS-----S-SSSSSS-SSS---S--SS-SS--S-S-S-SS----S-SS---SSS--S-S-S--SSSS-S--S-S----S---SSSSS---S----S-S---SSSSSS-S-S-SS-SS--S-S--SSSS--S----SS-SSSS-S----SS------SSS-]",
		"[S-S--SS---S--S-----SS-SSS-S-SSSSSS---S-SSSS---S-S-S--SS-S-S----S-SSS--S-----SS---SS-S--SS-SS--SSS-S--S--SSS-SSSSSSSS-S----S-S--SS--S-SSSS---S--S-------S---S---S-----SSS--S-SSS-S-----S--S-SSSSSS--S-S--S-SSSSSS---S--S-S-SSSSS---S-S----S-S-----S--SS-SSS-SS-S-SS-S-S-SS-S-S-S--S-SSSSSS-SS-S-S---SSSSS--S--SSS---S-----S----SS--SS--SSSS-SSSSS-SSS-SSSS-S-SSS--S--S----SS-S---S----S--SS-SS------S-SSS--SSS--SS-S--S-SSS--------SS---S-SSS---SS---S---S---SSS-SS-SS--S--S-SS----S-SSSSS------S--SS-SS-----S---SS--S------S-----SSSS--S--S-S--------S--S-SS-S-S-----S----SS-SSS-SS-----SS----S----S-S---S-----S-----S-SSSSS--SSS---S--SS-S---S-S-S-SS------SS---SSS--S-S-S--SSSSSS--SS--S--S---SSSSS---S----S-S----SSSSS-S-S-SSSSSS-S-S--SSS---S-S--SSSSSSS-S--S-SS------SSS-]",
		"[S----SS---S-----SS-SS--S--S-SS---S----SSSS-S--S-S-S---S-S-S-S--S---S--S-----S-----S-S-----S--SSSS-S-SS----S---SSSSSS-S----S----S-----SS-----S--S--S----------S-------SSS--S--S--SS----S-SS-SSSSSSS-S--S-S--SSSSS---SS-S-S-S-SSS---S------S-------SS-SS-S-S-S--S--SSS-S--S---S------SSS-SSSS--S-S-----SS-S-----S----SS----S-S-SSS-S-S-SSS-S-SS-SS-SSS-S-S--S-SS---S------SSS--------------S--S------SSS-S--S--S-SSSS--S-SS-----S--SSS---S-S-S---SS----S--S-SSSSS-S-SS---S--S-SS----S-SSSSS----S-S--SS-SS-----SS--SS--S------S-----SSS---S--S-S--------S-SS-SS-S-S--S-SS----SS-S-S-SS-----SS----S----S-S---S-----S------SSSS-SS-S-S--S--SSS-S---S-S-S-SS----S-SS-----S--S---SS-SSSS-S--S-S--------SS--S---SS---S-S----SSSSS---S-S-SSS--SS---SSSSS-S-S-----S-S--S----SS------SSS-]",

		// nrp5
		"[SS-SSSSS--S-SS---S-S-SSSSSSSSSS----SSSSSS-S-SS--SSSSS-S-SSS---S-SSS--S-SSSS-SS--SSSSS--SSS-SS-S-SSS--S---S-S-SS--SSSSS-S-S-S---SSSSSS-S-S-SSS-S-SSSS-S-S---SSSSSSSSS----S-SSS---SS-SS-S---S-SSSSS--S---SS-SSSS-SS-SSSS-S-SS-SSSSS-S-SS-S--SS-S-S-SSSS--S-SSS-SSSS---S-SS-SSS-SSSSSS--SSSSSS-S-SS-S--S-S--SS-SSSSSS-SSSSS-----SS-S-----SSS-SSS--SSSSS-SS-SSSSSSS-S---SSS-SSS-SS---S-SS---S-SSS--S-SSS-SSS-SSSS--SSSSSSSSS--SS---SSS-SSSSSS---SSSSS--SSS-S-S-SSS--SSSS-SSS-SSS-SS-SSSS-S-SSSSSSSSSSS----SS-SSSSSS-S-S-S---SS--S-S-----S-SSS-SS-SSSSSS-SSSS--SS-SSS--S--SSSSS-SSSSSSSSSSS-SSS-S-S-S--------S---SS--SSSS-SS--S-SSSS----SSS--SS-SSS--SSSS--SSS-SSS-S--SSS--S-SSSSSS-S----SSS-SSS---S----SSS----SSSSS-S-S-S-S-SSSS-SSSS-S--SSSS--S-S-S----S-SSS--SSS--S-----S-SSS-SS--S--SSSS-S-SSS-S-SSS-S-S-SSSSS----S-SS---SS-S-S-S-SSSSSS-SSSS---S--S-SSSSSSSSSSS-S-SS-S-S--SS-SSS-S---SS---SSSSSSS-S-S----SS-SSS--SSS--SS-SSS--SS-S-S-S--SSS-S--S-SS-S-S-SS--SS-S------S----S-----S--SSS-SS--SS--S---SSSSSSSS-SSSS--S-S-S--S-S--S-S-SS--S]",
		"[SSSS-SSSS-SSSS-SSS---SSS-SSSSSS--S-SSSSSSSS-S---SSS-S-S-SSSS--S-SS---S-SSSSSSS--SSSSS---SS-SS-S-SS--SS---S-S-S---SSSSSS--S-S---SSSSSS--SSS--S-S-SSSS-S-S---SSSSSSS------S-S-S---SSSSS-S---S--SSSSSSSS--SS-SSSS--S-SSSS-SSSS-SSSSS-S-SS--S-SS-S-S-SSSS--S-SSS-SSSS--SS----SSS--S-SSS--SSSSSSSS-SS-S--S-S--SSSSSSSS--SSSSS----SSS-S-S-S-SS--SSS-SSSSSS-SS-SSSSSSS-S--SSSS-SSS-SS---S-SS---S-SSS--S-S-S-SSS-SSSS--SS-SSS-SS--SS---SSS-SSSSSSS--SSSSS--SSS--S--SSS--SSSS-SSS-S-S-SS-SSSS-S-SSSS-SSSSSS----SSSSSSSSS-S-SS--S-SS--S--S----SSSSS--S-SSSSSSSS-SS--SS-SSS-SS--SSSSS-SSSSS-S-SSS-SSS-S-S-S-----S--S---SS--SSSS-SS-SS-S-SS--S-SSS--SS-SSS-SSSSS--SSS-S-S-S--SSS--S-S-SSSS-SS-S--SSSSSS---S----SSSS-S-SSSSS-S-S-SSSS-SSS-SS-S-S--SSSS-SS------S-S-SSS----S----SS-----SSSS---S-SSSSSSS--S--S-SSSSSSS-SSSSS------SS---SS-SSS-S-SSSSSSSSSSS---SS-S-S--SSSS-SSSSS-SS-S-S---S-SS--S---SS-S-SSSSSSS---S-S-SS-S-SS--SSS-SSS-SSS---SSSSS-S-S-SSSSSS--S--S---SS--SSSS------SS---------S--SS--SS--SS--S---SSSSSSSS-SSSS--S-S-S--S-S-S--S-SS--S]",
		"[-SSSSSSS-SSSS--S-S---SSSSSSS-SS--SSSSSSS-S--SS--SSS-S-S-SSS---S-S-S--S-SSS-SSS--SS-SS---SS-S--SSSS--SS---S-SSS----SSSSS--S-S-SS-SSSSS-S-S-S--SS-SSSS-S-S------SSSS-S-----SS-S----S-S--SSS-S--SSS-S-S---SS-SS----S-S--S-SSS--SSSSS-S-SS----SS-SS--SSSSSSS-SSS-SSSS--S-----SSS--SSSSS--SSSSSS-S-SS-S--S-SS--S-S-SSS--SSSSS-----SS---S---SS--SSS-SSSSSS-SS-SSS--S--S---SSS-SSSSSSSS-S-SS---S-SSS--S-S-S-SSS--S-S--SS-SSS--S--S--SS--S-SSSSS----SSS-S-SSSS---S-SSS---SSS--SS-S-S-SS-SS-S-S-SS-S-SSSSSS--S--S-SSS-SS-S--SS-------S--S----SSSSS--S-S-SSSSSSSS--SSSS-SSSSS--SSSSS-SS-SSSS--S--SSS--SSSS----S---SS---S--S-SS-S-----SSSS-S--SSS-SS---SS--SSSS--S-S-S-S-S--SSS--S-S-SSSS-SSSS-----SSS---S----SSSS-S-S-SSS-SS--S-S--S-S--SSS-SS-SSSS-SS--S---S-S--S-----S----S-S----S-SS---S--SSSS-S-----S--SSSS-S-SSS-S-S-S--SS--SSS-S-----S--S--SSSSS---S-SS-S-SSSSS-SSS-SS-S-S-S--S--SSS-S---SS---SS-SS--S--S-S--SS--S----SS---S-S-S-S-S-SSS-S-S-SSSS-SS-SS-S---SS--SSSS------SS---S-----S--SS--SS--SS--SS--SSSSSS-S-SSSS--S-S-S--S-S--SS--SS--S]"
	};

	/**
	 * Best solutions generated by VISILS
	 */
	private static String[] VISILS_CRO_INSTANCES =
	{
		// nrp1
		"[--SSSS-S--S-----SS---S-----SS-SS-S---S----S---S----S----SS-SS-SSSS--S-SS--SS-S-S--S-SS-S-SS----S-S--]",
		"[---SSS-SS-S-----SS-S----S-S---SS----SS----S---S----S--------SS-SSS--S-SSS-SS-S-S--S-SS-S-SS-S--S-S--]",
		"[-S-SSS-S--S----SSS----S---S---------SS----SS--SS---S---------S-S-S--S-S-S--S---S--S-SS-S-SS----S-S--]",

		// nrp2
		"[S-S-S-SSS------S-----S-S--S--S-----S----SSS--S----S-------S-SS-S-SS--------S-SS-S---SS-SS-------------S--SS---S-------S-S--S--S---S-SS---------S--S-SS-S--S--S--S----------S---SS-S--S---S-S-S--SS--S---SSS--S---S--S----S---SS-S--S-SSS-S--SS---S-S-----S--S-S---------------S----SSSS-SS----SS---SSS---S-S--------S-S-SS--SSS--SS-----S--S-S--S----S-S-----S------SS-SS-S--S-----S--SS-S-S-S--SS-S------SS--S-S--SS-SS----S-------S--SS---S-----S-SS--SS-S-------S-SS--SS----S----S---SS-------S-------S--S-SS-S--]",
		"[S-S-S-SS-------SS----S-S--SSSS-----S-----SS--S----S-------S----SS-S-SS-----S--S-S---SS--S-S-------S---S--SS---SS------S----S--SS--SSSS---S-----S--S-S-SS--S--S--S-S--------S---SS-S--SS-SS---S--S---S---SSSS-S---S--S--S-S---SS----S--SS-S--S----S-S--------S-S--S--------S---S----SS-S--S----SSSS-SSS-----S--------S-S-SS-S-SS--SS-----S--S-SS-S----S-S-----S------S--SS-S-SS-----S--SS-----S--SS---------S--S-S---S-SS----S----S-SS--SS---SS----S-S-S-S--S-------S-SS--SS---------S----S-------S----------SSSSSS--]",
		"[S-----S--------SS---SS-------SS----S-----SS-------S-------S----S--S-S------S----S---SS-SS-------------SS--S---SS-----------S--S---S-SS---S-----SS---SS-S--S--S--S----------S---S--S-----SS--SS--S---S---SSS------S--S----S--SSS-SS-SS-SS----S----S-S----------SS-S--S----S----S----S-SS--S----SS---S-SS--S----------S-SS-S----S--SS---S-S----S--S----S-S-S---S------S--SS-S--S--------S------S--S--S----------S-----S-SS----S-------S--SS----S--S-S-S-S-SS--S------S--S--SS----S-S--S---SS-S-----S----------S-SS-S--]",

		// nrp3
		"[-SSS-SSS-S-S--S-S--S--SS-S-S---SSS--SS--S-SS----S---S-S-S---S-SS-S--SS-SS-S-----S--S-SS--SS-SSSS--S----SSSS--SSSSS--S----S-SS-SSSSSS-SS--SSSS---SSSS-S-SS-S--S--S---S---SSSSS-SSSSSS-S-SSSSSS---S-SS-S-SS-S---SS-SS-SS---SS-S--S---S-S--S-SS-SSSS-S----S-S-S-S--------SS-S----SSSSS--SS-----S-SS-S-SSS-S----S-S-S---SS-----SS--SSS-S--S---S--SS-S-S----S-SS-S-SS----SS----S-SS-S---SS-S-SS--SSSSSS---S--S----S----SSS--S-S--S-S-SS----SS-S-SS----S-SS-SSSSSSSS-S-S----S----S---S-SS--S-S-S-SS---S-S-SSSS-SSSS---SSS-]",
		"[-SSSSSSS-S-S--S-S--S--SS-S-----SS---SS--S-SSS---S---S-S-S---S--S----SS-S--S-S---S----SS--S--SSSS--S----SS-SSSSSSS-S------S-SS-S-SSSS-SSS-SSSS-S-SSSS-S-S--S--SS-S--SS---SSSSS-SSSSSSSS-SSSS-S----SSS-S-SSSS---SS-SS--S------S--S---S-S--SSSS-SS---S--SS--S-SSS--------SS-SS-S-SSSSS-SSS----S--SS-S-SS--S----SSS-S---SS-S--SSS--SS---------S--S---SS----S--S---SS-----SS---S-SS-S--SS--S-SS--SSSS-S--SS-SS----S---SSSS-SS-S--SSS--S-S-SSS-S-SS----S-SS-SSSSS-SS-S-S-S-------S---S-SSS-S-S-S-SS---S-S-SSSS--SSS----SS-]",
		"[--SS-SSS-S-S--S-S--S--SS-S-----SSS--SSS---SS----S---S---S---SS-SS-S-SS-S--S-S---S--S-SSS-S--SSSS--S----S-S--S-S-----SS---S-SS---SSSS--S---S-S----S---S-S-----SSSS---S----SSSS-SS-SSSSS--SSS-S----SSS-S-SSSS---SS--S-S--S-------S-----S--SS---SS---S---S------S-S------S--S-----SSS--SSS--------S-SS-SS----S-SS--S-S-SSSSS---S--SS-S---S---SS-----SS----S----S-SS-SSSSSS---S-----------S-SS--SSSS-S------S-SS---S-S-S--S--S--SS--SS-S--S-S---SS---S-S--SSSSS-SS-S-S-SS-S--------S-SS-SS---S-SS-S-S-SSSSSS--SSS--S-SS-]",

		// nrp4
		"[S-S--SS---S--------SS-SSS-S-SSS--S-S-S--SSS---S-S-S--S-SS-S----S-S----S-----SS-S-SS-S-SSS-SS--SSS-SS--SSSSS--SSSSSSS-S------S--SS----SSSS---S--S-------S---SS--SS---SSSS--S-SSS-S-----S-SS-SSSSSS--S-S----SSSSSS-S-SS-S-S-SSSSS---S-S----SS-----S---SS-SSS-SS-S-SS-S-SS-S-S-S----S--SS-SS-SS-S-S----SSSS------SS---SS----S----SSS--S-SSS-S-SSSSS-SSS-SSSS-S-SS------S----SS-SS-SS--SS-S--S-SS------SSSSS--SSSS-SS-S--S-SSS--------SS---S-S-S-SSSS---S-S-S---SSS-SS-SS--S--S-SSS---S-SSS-S---S--S--SS-SS-----S---SS--S------S------SSS--S-SS-S-------SS--S-SS-S-SS--------SS-SSSS-SSS--SSSS----S----S-S---S-----S-----S--SS-S--SSS---S--SS-SS--S-S-S-SS--S---SS---SSS--SSS-S--SSSS-S--SSS----S---SSS-S--SS----S-S---SSSSSS-S-S-SS-SS--S-S--SSS---S-S-SSS-SSSS-S----SS-S----SSS-]",
		"[S-S--SS---S--------SS-SSS-S-SSSS-S---S--SSS---S-S-S--SSSS-S----S-SS-S-S-----SS---SS-S--S--SS--SSS-SSS-SSSSS--SSSSSS--S------S--SS--S-SSSS---S--S--S----S---S---SS----S-S--S-SSS-S-----S-SS-SSSSSS--S-S--S-SSSSSS---S--S-S-SSS-S---S-S----SSS--------SS-S-S-SS-S-SS-S-S--S-S-S-S--S--SS-SS-SS-S-S---SSSSS---S-SSS---SS---SS----SSSSSS-SSS-S-SSSSS-SSS-SSSS-S-SS------S----SS-SS--S---S-S--S-SS------S-SSS--SSS--SS-S--S-SSS--------SS-S-S-S-S---SS---S---S---SSS-SS-SS--S--S-SSS---S-SSSSS---S--S--SS-SS-----S---SS--S------S-----SSSS--S-SS-S-----S-S---S-SS-S-SS-----S--SS--SS--SSS--SSSS----S----SSS--SS----SS-S---S-SSSSS--SSS---S--SSSSS--S-S-S-S-------SS---SSS--SSS-S--SSSS----SS--S--S---SS--S--SS----S-S----SSSSS-S-S-SS-SSS-S-S--SSS---S-S--SS-SSSS-S-----S----S-SSS-]",
		"[S----SS---S-----SS-SS-SS--S--SS-SS-----SSS----S-S-----SSS-S-S--S---S--------S-----S-S-----S---SSSSS-SS-S--S--SSSSSSS-S----S----S---S-SS-----S--SS-S--------S---S-----SSS--S--S--SS----S-SS-SSSSSSS------S--SSSSS---SS-S-S-S-SSS---S----S-S-S-----S--SS-S-S-S--S--SSS-S--S---S-S-----SS-SSSSS-S-S----SSS------S-SS--SS----S-S--S--SSS-SSSSS-SS-SS-SSS-S-S--S-SS---S--S----SS--------------S--S--S---SSS-S--SSS--SS-S--S-SS---------SS---S-S-S---SS---SS--S-S-SSS-S--S---S--S-SS----S-SSSSS------SSSSS-SS-----SS-SSS-SS------SS----SSS---S-SS-S-------SS-SS-SS-S-S--S-SS-S--S--S---SS-----SS----S----SSS---S-----S-S----SSSSS--SS-S--S---SS-----S-S-S-SS------SS---S-S--S-S-S--SSSS-S--S---S------SSS-S---S----S-S----SSSSS---S-S--SSS-S----SSS---S-------S-S--S-S--SS------SSSS]",

		// nrp5
		"[SSSS-SSSSSS-SS-S-S-S-SSSSSSSSSS-S-SSSSSSSS--SSS-SSSSS-S-SSSS--S-SSS-SS-SSSSSSS--SSSSS--SSS-SS-S-SS---S-SSS-S-S---S-SSSS--SSS---S-SSSS-S-SSS---S-SSSS-S-S----SSSSSS-S------SSS---SSSSS-S---SS-SSSSSSS---SS-SSSS-SS-SSSS-SSSS-SSSSS-S-SS-S--SS-S-S-SS-S-SS-SSS-SSSS---S-S--SSS---SSSS--SSSSSS---SS-S----S---SSSSSSSS-SSS-S-----SS-S---S-SS--SSSS-SSSSS-SS-SSSSSS------SSSSSSSSS----S-SS---SSSSS--S-SSSSSSS-SSSS--SS-SSSSSS--SS---SSS-SSSSSSSSSSSSSS--SSS--SS-SSS--SSSSSSSS-SSS-SS-SSSS-S-SSSSSSSSSSS--S-SSSSSSSSS-S-SSS---SS--S--S----SS-SS--S-SSSSSSSSSSS--SSSSSS-SS--SSSSS-SS-SSSSSSSS-SS-SS-S-S-----S--S---SSS-SS-S-SS--S-SSSS-S--SSS--SS-SSS-SSSSS--SSS-SSS-S-SS-S--S-SSSSSS-S--SSSS--SSS---S----SSS--S-SSSSS-S-S-SSS--SSS---SS-S--S-SSSSS-S------S-SSSS---S-----S-----SS-SS--S--SSSS-S-SS--S-SSS-S-S-SSSSS------SS----SSS-S-S-SSSSSS-SSSS---S--S-S-SSSS-SSSS-S-SS-S-S---S--S-SS---SS---SSSSS-SS--S----SSS-S---SSS-SSS-SSS---SSS---SS-SSS-SS-S-SS-S-S-SS--SS-S------SS---S-S---S--SS--SS--SS-SSS--SSSSSSSS-SSSS--S-S-S--S-S----S-SS--S]",
		"[SS-SSSSS--S-SS---S-S-SSSSSSSSSS----SSSSS-S--S-S-SSSSS-S-SSS---S-S-S--S-SSSSSSS--SSSSS--SSS-S--S-SS---S-S-S-SSS----SSSSS--SSS---SSSSSS--SS-----S-SSSS-S-S-S--SSSSSS-S----S-SSS-SSSSSSS-S---S--SSSS-SS---SS-SSSS-SS-SS-S-SSSS-SSSSS-S-SS-S--SS-S-S-SSSSS-S-SSS-SSSS---S-SS--SS--SSSSS--SSS-SSS-SSS-S--S-S--SS-SSSSSS-SSS-S-S---SS-S---S-SSS-SSSS-SSSSS-SS-SSS-S-S-S---SSS-SSS-SS-S-S-SS---S-SSS--S-SSS-SSS-SSSS--SS-SSS-SS--SS-SSSSS-SSS-SS-S-SSS-S--SSS--S--SSS--SSSSS-SS-S-S-SS-SSS--S-SSSS-SSSSSS----SSSSSSSSS-S-SSS---SSS-S-SS----SS-SS--S-SSSSSS-SSSS--S--SSSSSS--SSSSS-SSSSS-S-SS--SSSSS-S-S--------S---SSS-S-SS-SS--S-S-SS-S--SSS--SSSSSSS-SSSS--SSS-SSS-S-SSSS--S-SSSSSS-S--S--SS-SSS---S----SSS--S-SSSSS-S-S-SSS-SSSS---SS-S--SSSS-SS-S------S-SSS--S-S--S--S--S-SSS-SS--S-SSSSS-S-SS--S-SSS-SSS-SSSSS-S-----S----SSS-S-S-SSSSSSSSSSS---S-SS-S-SSSSS-SSSSS-SS-S-S---S--S--S---SS---SS-SSSSS--S-S--SSS-S---SSS-SSS-SSS-S-S-S---S--SSS-SS-S-SS-S-S-SS---S-S------SS---S-----S-SSS--SS--SS-SS-S-SSSSSSSS-SSSS--S-S-S--S-S-SS-SSSS--S]",
		"[-SSSSSSS--S-S----S-S-SSS-S-S-SS--SSSSSSS-S--S---SS--S-S-SSSS----S-S--S-SSS-SSS--SS-SS---SS-S--SSSS--SS---SSSSSS---SSSS-S-S-S-----SSSS-SSS-S---S-SSSS-SSS---S--SSSS-S---SS-S-S-S--S-S--SS--S--SSSSS-S---SS-SSS---S-S-SS-SSS--SSSSS-S-SS----S--S---SS-S--S-SSS-SSSS--S---S-SSS--SS-SS--SSSSSSSS-SSSS----S---S-S-SSS--SSS-S-S---SS---S---SSS-SSS--SSSSS-SS-SSS--SS-S---SSS-SSS-SSS--S-SS-----SSS--S-S-S-SSS-SSSS--SS-SSS--S--S--S---S-SSSSS-----SS-S-SSSSS--S-SSS---SSS---S-S---SS-SS-SSS-SSSS-SSSSSS--S--S-SSS-SS-S--SS-------S-SS----SSSSS--S-S-SSSSSSSS---SS--SS-SSS-SSSSS-SS-SSSS--S-SSS-S-S--S----S---S----S--S--S-S-----S-SSS---SSS--S---SSS-SSSS--S-S-S---S--SSS--S-SSS-SS-SSSS----S-SS---S----SSS--S-S-SSS-S---S-SSSS-SS--SS-SS-SSSS-SS--SSS-S-S--S-----S--S-S---S-SS-SSS--S-SSSSS-S---SSS--SSSSSS-SSS-S-SS---SS--S-S-SS----S-SS--SSSSS---SS-S-SSSSSS--SSS-S--S-S-SSSS---SS-S---SS---SS-SS-----S----SS--SSS-SSS---S-S-S-S-S-S-S-S-SSSS-SSSS-SS-S-S-SS--SSSS-S----SS---S--S--S--SSS-SS--SS--SS--SSSSSS-S-SSSS--S-S-S--S-S--SS-SSS--S]"
	};

	/**
	 * Best solutions generated using profit-only optimization
	 */
	private static String[] OP_INSTANCES =
	{
		"[--SSSS-S--S-----SS---S-----S--SS-S---S----S---S----S----SS-SS-SSSS--SSSS--SS-S-S--S-SS-S-SS----S-S--]",
		"[S-S-S-SS-------SS----S-S-S-S-S-----S----SSS--S----S-------S--S--SSS-SS-----S-SS-----S---S-S-----------S--SS---S-------S-S--S--SS--SSSS---S----SS--S--S-S--S--S--S--S-------S---SS----SS-SS--S--SSS--S---SSS--S---S--S--S-S---SS-S--S--SS---SSS---SSS-----S----S-------S--SS---------SSS--S----SSSS-SSS-----S--------S-S-SS-S-S----S----S-----S--S----S-S-----S------S--SS-S-SS-----S--SS-----S--SS--------SS--S-S--SS-S-----S------SS---S---SSS---S-S-S--S-SS------S-SS--SS----S----S----S-------S-------S--SSSSS---]",
		"[-SSS--SS-S-S--S----S--SS-S-S---SSS--SS--S-S-S---S---S-S-S---S-SS----SS-S--S-S---S---SSS--SS-SSSSS-S----SSSS--SSSSSS-S----S-SS-SS-SSS-SSS-SSSS--SSSSS-S-SS-S-----S---S---SSSSS-S-SS-S-S-SSSS-S-----SS-S-SS-S---SS-SS--S---------S--SS-S--S-SS-SSS--S--SS----S-S--------SS-SS--SSSSSS--SS----SS-SS-S-SSS-S----S-S-S-S-SS-S---SS--SSSS-------SS-S----S----S-SS-S-SS-S---SS---S-SS-S--SSS-S-SS--SSSSSS---S-SS----S----SSS-SS-S--S-S--S---SSS-S-SS--SSS-SS-SSSSS-SS-S-S-S-------S---S--S--S-S-S-SS---S-S-SSSS-SSSS-SSSSS-]",
		"[S-S--SS---S--S-----SS--SS-S---SS-SS--S--SSS-S-S-S----SS-S-S-S--S-SSSS-S-----S----SS---S-S-SS--SSS-SS-SS-SSS--SSSS-SS-S----S-S--SS----SSSS---S--S--S----S---SS--SS----SSS--S-SSS-S-----S--SSSSS-SS--S-S----SSSSSS-S-S--S-S-S-SSS---S-S----SS---------SS-SSS-SS-S-SS-S-S--S-S-S----S---S-SS-SS-S-S---SSSSS-----SSS--S------S----SS--SS-SSSSS-S-SSS-SSS-SSSS-S-S----S--S-----S-S--SS---S----S-SS--S---S-SSS--SSSS-SS-S--S-SSS--------SS---S-S---S-SS---S---S---SSS-SSSSS-----S-SS---SS-SSS-S------S--SS-SSS-S--S---SS-SS------S----SSSS---S--S-S-----S-SS--S-SS-S-SS----S----SS-SS--SSS--SSSS----S-----S---SSS-S-SS-----S-SSSSS--SSS---S--SS-SS--S-SSS-SS---SS-SS---SSS--SSS-S--SSSSSS--S-S--------SSSSS--SS----S-S---SSSSSS-S-S-SS-SS--SSS--SSS---S----SSSSSSS-S----S--S----SSSS]",
		"[SSSS-SSSS-S-SS-S-S-S-SSSSSSSSSS-SS-SSSSSSS--S-SSSSS-S-S-SSSS--S-S-S-SS-SSSSSSS--SSSSS--SSSSS--S-SS---SS--SSS-S---S-SSS---SSSS--S-SSSS-S-SSSSS-S-SSSS-SSS----SSSSSSS-----S-S-S---SSSSS-----S-SSSSSSSS---SS-SSSS-SS-SSSS-SSSS-SSSSS-S-SS----SS-S-S-SS-S--S-SSS-SSSS-S-S-S----S--SSSSS---SSSSS-S-SS-S----S---SSSSSSSS-SSS-S--S-SSS-SS--S-SS--SSSSSSSSSS--S-SSSSSSS-S---SSS-SSS-S---SS-SS---S-SSS-SSSSSS-SSS-SSSS--SS-SSSSSS--SS--SSSS-SSSSSSSS-SSS-SS-SSS--SS-SSS--SSSS-S-S-S---SS-SSS--S-SSSS-SSSSSSS---SSSSSSSSS-S-SS-S--SS--S--S----SSSSS--S-SSSSSSSS-SS--SS-SSS--SS-SSSSS-SS--SSS-SS--SS--SSS-S-----S--S---SS--SS-S-SS--S-S-SS-S--SSS--SS-SSSSSSSSS--SSS-SSS-S-SS-S--S-SSSSSS-SSS---S--SSS---S--S-SSS--S-SSSSS-SSS-SSS--SSS----S-S--SSSS--SSS------S-SSS--SSS----SS-----SS-SS-SS--SSSSSS-SS--S-SSS-SSS-SSSSS------SS--S-SSS-S-S-SSS-SS-SSSSS--S-SS-S-SSSS--SSSSS-SS-S-S-SSS--SS-----SS---SSSSS-SSS---S--SSS-S-S-SSSSSSS-SSS---SSS---S--SSS-SS-S-S--SSS-SS---S-S------SS---S-SS--S--SS--SS-SSS--S---SSSS-SS--SSSS----S-S--SSS-S--S-SS---]"
	};

	/**
	 * Runs the analysis
	 */
	public void execute()
	{
		handleInstance(Instance.NRP1, 0);
		handleInstance(Instance.NRP2, 1);
		handleInstance(Instance.NRP3, 2);
		handleInstance(Instance.NRP4, 3);
		handleInstance(Instance.NRP5, 4);
	}
	
	/**
	 * Runs the analysis for all instances
	 */
	private void handleInstance(Instance instance, int opIndex)
	{
		int ocrIndex = opIndex * 3;
		handleInstance(instance, 30, 10, ILS_CRO_INSTANCES[ocrIndex], VISILS_CRO_INSTANCES[ocrIndex], OP_INSTANCES[opIndex]);
		handleInstance(instance, 30, 20, ILS_CRO_INSTANCES[ocrIndex+1], VISILS_CRO_INSTANCES[ocrIndex+1], OP_INSTANCES[opIndex]);
		handleInstance(instance, 30, 40, ILS_CRO_INSTANCES[ocrIndex+2], VISILS_CRO_INSTANCES[ocrIndex+2], OP_INSTANCES[opIndex]);
	}
	
	/**
	 * Runs the analysis for an instance under optimization constraints
	 */
	private void handleInstance(Instance instance, int budgetFactor, int riskImportance, String bestILS, String bestVISILS, String bestProfit)
	{
		MaximumValuesList maximumValues = new MaximumValuesReader().execute();
		MaximumValues values = maximumValues.getMaximumValues(instance, budgetFactor);

		RequirementReader reader = new RequirementReader();
		Project project = reader.execute(instance);

		int availableBudget = (int) (project.getTotalCost() * (budgetFactor / 100.0));
		ProfitRiskFitnessCalculator oprCalculator = new ProfitRiskFitnessCalculator(project, availableBudget, riskImportance, values.getMaximumProfit(), values.getMaximumProfitRisk());
		
		Solution solutionBestILS = new Solution(project);
		solutionBestILS.fromString(bestILS);
		double fitnessILS = oprCalculator.evaluate(solutionBestILS);
		double profitILS = project.calculateProfit(solutionBestILS.getSolution());
		double riskILS = project.calculateProfitRisk(solutionBestILS.getSolution());
		
		Solution solutionBestVISILS = new Solution(project);
		solutionBestVISILS.fromString(bestVISILS);
		double fitnessVISILS = oprCalculator.evaluate(solutionBestVISILS);
		double profitVISILS = project.calculateProfit(solutionBestVISILS.getSolution());
		double riskVISILS = project.calculateProfitRisk(solutionBestVISILS.getSolution());
		
		Solution solutionBestProfit = new Solution(project);
		solutionBestProfit.fromString(bestProfit);
		double fitnessProfit = oprCalculator.evaluate(solutionBestProfit);
		double profitProfit = project.calculateProfit(solutionBestProfit.getSolution());
		double riskProfit = project.calculateProfitRisk(solutionBestProfit.getSolution());
		
		System.out.print(instance.name() + "\t" + budgetFactor + "\t" + riskImportance + "\t");
		System.out.print(fitnessILS + "\t" + profitILS + "\t" + riskILS + "\t");
		System.out.print(fitnessVISILS + "\t" + profitVISILS + "\t" + riskVISILS + "\t");
		System.out.print(fitnessProfit + "\t" + profitProfit + "\t" + riskProfit + "\n");
	}
}